"use client";

import React, { useEffect, useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Info, TrendingUp, Wallet, Banknote, ShieldCheck, ArrowRight } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

interface YieldSource {
  id: string;
  name: string;
  value: number;
  percentage: number;
  color: string;
  description: string;
}

interface YieldBreakdown {
  totalApy: number;
  lastUpdate: string;
  sources: YieldSource[];
}

const sourceIcons: Record<string, React.ReactNode> = {
  lending: <Banknote className="w-4 h-4" />,
  staking: <TrendingUp className="w-4 h-4" />,
  lp_fees: <Wallet className="w-4 h-4" />,
  vol_shield: <ShieldCheck className="w-4 h-4" />,
};

export function PerformanceAttribution() {
  const [data, setData] = useState<YieldBreakdown | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    
    async function fetchData() {
      try {
        const response = await fetch('/api/ai/yield-breakdown');
        if (!response.ok) throw new Error('Failed to fetch yield breakdown');
        const breakdown = await response.json();
        if (mounted) {
          setData(breakdown);
          setLoading(false);
        }
      } catch (err) {
        if (mounted) {
          setError(err instanceof Error ? err.message : 'Unknown error');
          setLoading(false);
        }
      }
    }

    fetchData();
    return () => { mounted = false; };
  }, []);

  if (error) {
    return (
      <Card className="border-destructive/20 bg-destructive/5">
        <CardContent className="pt-6">
          <div className="flex items-center gap-2 text-destructive">
            <Info className="w-4 h-4" />
            <p className="text-sm font-medium">Error: {error}</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="overflow-hidden">
      <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
        <div>
          <CardTitle className="text-xl font-bold flex items-center gap-2">
            Performance Attribution
            <span className="text-xs font-normal text-muted-foreground bg-muted px-2 py-0.5 rounded-full uppercase tracking-wider">
              AI Powered
            </span>
          </CardTitle>
          <CardDescription>
            Live breakdown of yield sources generated by the XHedge engine
          </CardDescription>
        </div>
        <div className="text-right">
          <div className="text-2xl font-bold text-primary">
            {loading ? <Skeleton className="h-8 w-16 ml-auto" /> : `${data?.totalApy}%`}
          </div>
          <div className="text-[10px] text-muted-foreground uppercase font-semibold">
            Composite APY
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-4">
        <div className="space-y-6">
          {loading ? (
            Array(4).fill(0).map((_, i) => (
              <div key={i} className="space-y-2">
                <div className="flex justify-between items-center">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-4 w-12" />
                </div>
                <Skeleton className="h-2 w-full" />
              </div>
            ))
          ) : (
            data?.sources.map((source) => (
              <div key={source.id} className="group relative">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <div 
                      className="p-1.5 rounded-md bg-muted group-hover:bg-primary/10 transition-colors"
                      style={{ color: source.color }}
                    >
                      {sourceIcons[source.id] || <div className="w-4 h-4 bg-current rounded-sm opacity-20" />}
                    </div>
                    <div>
                      <span className="text-sm font-semibold text-foreground">{source.name}</span>
                      <p className="text-[10px] text-muted-foreground">{source.description}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="text-sm font-bold text-foreground">{source.value}%</span>
                    <p className="text-[10px] text-muted-foreground">{source.percentage}% share</p>
                  </div>
                </div>
                <div className="relative h-1.5 w-full bg-muted rounded-full overflow-hidden">
                  <div 
                    className="absolute top-0 left-0 h-full rounded-full transition-all duration-1000 ease-out"
                    style={{ 
                      width: `${source.percentage}%`,
                      backgroundColor: source.color 
                    }}
                  />
                </div>
              </div>
            ))
          )}
        </div>
      </CardContent>
    </Card>
  );
}
